---
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest
      username: ((docker_hub_username))
      password: ((docker_hub_authtoken))

resources:
  - name: govuk-speedcurve-lux-js-monitor-git
    type: git
    source:
      uri: https://github.com/alphagov/govuk-speedcurve-lux-js-monitor.git
      branch: master

  - name: every-8h
    type: time
    source:
      interval: 8h

  - name: govuk-frontenders-slack
    type: slack-notification
    source:
      url: ((govuk_platform_health_slack_webhook_url))

jobs:
  - name: update-pipeline
    plan:
      - get: govuk-speedcurve-lux-js-monitor-git
        trigger: true
      - set_pipeline: govuk-speedcurve-lux-js-monitor
        file: govuk-speedcurve-lux-js-monitor-git/concourse.yml

  - name: speedcurve-monitor
    plan:
      - get: every-8h
        trigger: true
      - task: Speedcurve monitor
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ruby
              tag: 2.6.6
              username: ((docker_hub_username))
              password: ((docker_hub_authtoken))
          run:
            path: sh
            args:
              - -c
              - |
                curl https://cdn.speedcurve.com/js/lux.js\?id\=47044334 | grep 't="216"' || exit 1
        on_failure:
          put: govuk-frontenders-slack
          params:
            channel: '#govuk-frontenders'
            username: 'Concourse (speedcurve lux js monitor)'
            icon_emoji: ':concourse:'
            silent: true
            text: |
              :kaboom: The Concourse SpeedCurve LUX monitor job has failed, this likely means the JavaScript needs updating.
              Failed build: http://cd.gds-reliability.engineering/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
              See https://github.com/alphagov/govuk-speedcurve-lux-js-monitor/ for more details of this job.
